//! Strongly typed session identifier.

use std::fmt;

use uuid::Uuid;

/// Session IDs are generated by the engine and must not be user-controlled.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct SessionId(Uuid);

impl SessionId {
    /// Generate a new random session identifier.
    ///
    /// # Returns
    /// * `Self` - A new session identifier.
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Parse a session identifier from a string.
    ///
    /// # Arguments
    /// * `input` (`&str`) - Input string to parse.
    ///
    /// # Errors
    /// `Option<Self>` - Returns `None` if the input is not a valid UUID.
    pub fn parse(input: &str) -> Option<Self> {
        Uuid::parse_str(input).ok().map(Self)
    }

    /// Get the raw bytes of the session identifier.
    ///
    /// # Returns
    /// * `[u8; 16]` - The session ID as raw bytes.
    pub fn as_bytes(&self) -> [u8; 16] {
        *self.0.as_bytes()
    }
}

impl fmt::Display for SessionId {
    /// Convert the session ID to a string.
    ///
    /// # Returns
    /// * `String` - The session ID as a string.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}", self.0)
    }
}

impl Default for SessionId {
    /// Generate a default session ID.
    ///
    /// # Returns
    /// * `Self` - A new random session ID.
    fn default() -> Self {
        Self::new()
    }
}
