name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Ensure cargo in PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install dependencies
        run: |
          cargo binstall -y \
            cargo-make \
            cargo-deny \
            cargo-audit \
            cargo-dylint \
            dylint-link

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run continuous integration tasks
        run: cargo make ci
