name: Miri

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"
  pull_request:
    branches:
      - master

concurrency:
  group: miri-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_HOME: /home/runner/.cargo
  CARGO_TERM_COLOR: always

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: miri
          cache-on-failure: true

      - name: Cache Miri sysroot
        uses: actions/cache@v4
        with:
          path: ~/.cache/miri
          key: miri-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}

      - name: Setup Miri
        run: cargo miri setup

      - name: Run Miri tests
        run: cargo miri test --all-features --all-targets
